### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by riyase** [PhilJay/ValueBar#9]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.voris.yara, PID: 31028
                                                                java.lang.NullPointerException
                                                                    at com.philjay.valuebar.Utils.calcTextHeight(Utils.java:102)
                                                                    at com.philjay.valuebar.ValueBar.drawValueText(ValueBar.java:212)
                                                                    at com.philjay.valuebar.ValueBar.onDraw(ValueBar.java:197)
                                                                    at android.view.View.draw(View.java:14681)
                                                                    at android.view.View.getDisplayList(View.java:13575)
                                                                    at android.view.View.getDisplayList(View.java:13617)
                                                                    at android.view.View.draw(View.java:14395)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
                                                                    at android.view.View.draw(View.java:14684)
                                                                    at android.widget.FrameLayout.draw(FrameLayout.java:472)
                                                                    at android.view.View.getDisplayList(View.java:13575)
                                                                    at android.view.View.getDisplayList(View.java:13617)
                                                                    at android.view.View.draw(View.java:14395)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
                                                                    at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3820)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
                                                                    at android.view.View.draw(View.java:14684)
                                                                    at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3290)
                                                                    at android.view.View.getDisplayList(View.java:13575)
                                                                    at android.view.View.getDisplayList(View.java:13617)
                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3211)
                                                                    at android.view.View.getDisplayList(View.java:13512)
                                                                    at android.view.View.getDisplayList(View.java:13617)
                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3211)
                                                                    at android.view.View.getDisplayList(View.java:13512)
                                                                    at android.view.View.getDisplayList(View.java:13617)
                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3211)
                                                                    at android.view.View.getDisplayList(View.java:13512)
                                                                    at android.view.View.getDisplayList(View.java:13617)
                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3211)
                                                                    at android.view.View.getDisplayList(View.java:13512)
                                                                    at android.view.View.getDisplayList(View.java:13617)
                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3211)
                                                                    at android.view.View.getDisplayList(View.java:13512)
                                                                    at android.view.View.getDisplayList(View.java:13617)
                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3211)
                                                                    at android.view.View.getDisplayList(View.java:13512)
                                                                    at android.view.View.getDisplayList(View.java:13617)
                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3211)
                                                                    at android.view.View.getDisplayList(View.java:13512)
                                                                    at android.view.View.getDisplayList(View.java:13617)
                                                                    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3211)
                                                                    at android.view.View.getDisplayList(View.java:13512)
                                                                    at android.view.View.getDisplayList(View.java:13617)
                                                                    at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
                                                                    at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
                                                                    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2551)
                                                                    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2417)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2006)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5993)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5584)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by riyase** [comment]
the issue was valuebar text was not set..
